//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/aaspr.DESKTOP-G6R73JT/OneDrive/Desktop/pomo/p4/alang_compile/core_compile\ALang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrGen {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class ALangParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		ENDIF=10, ENDREPEAT=11, ENDTERM=12, IF=13, ELSEIF=14, ELSE=15, REPEAT=16, 
		TIMES=17, THEN=18, TYPE=19, LPAREN=20, RPAREN=21, COMMA=22, ASSIGNOPERATOR=23, 
		OPALL=24, BOOLEAN=25, INTEGERS=26, PIN=27, ON=28, OFF=29, TIME=30, FLOAT=31, 
		ID=32, ALANGFILENAME=33, WHITESPACE=34, NEWLINE=35, BLOCKCOMMENT=36, LINECOMMENT=37;
	public const int
		RULE_start = 0, RULE_commands = 1, RULE_dcl = 2, RULE_function = 3, RULE_imports = 4, 
		RULE_primaryExpression = 5, RULE_expression = 6, RULE_params = 7, RULE_param = 8, 
		RULE_stmts = 9, RULE_assignstmt = 10, RULE_ifstmt = 11, RULE_repeatstmt = 12, 
		RULE_outputstmt = 13, RULE_returnstmt = 14, RULE_functioncall = 15, RULE_inputparams = 16, 
		RULE_value = 17;
	public static readonly string[] ruleNames = {
		"start", "commands", "dcl", "function", "imports", "primaryExpression", 
		"expression", "params", "param", "stmts", "assignstmt", "ifstmt", "repeatstmt", 
		"outputstmt", "returnstmt", "functioncall", "inputparams", "value"
	};

	private static readonly string[] _LiteralNames = {
		null, "'function'", "'->'", "'|'", "'endfunction'", "'import'", "'while'", 
		"'do'", "'endwhile'", "'return'", "'endif'", "'endrepeat'", "';'", "'if'", 
		"'else if'", "'else'", "'repeat'", "'times'", "'then'", null, "'('", "')'", 
		"','", "'='", null, null, null, null, "'ON'", "'OFF'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "ENDIF", "ENDREPEAT", 
		"ENDTERM", "IF", "ELSEIF", "ELSE", "REPEAT", "TIMES", "THEN", "TYPE", 
		"LPAREN", "RPAREN", "COMMA", "ASSIGNOPERATOR", "OPALL", "BOOLEAN", "INTEGERS", 
		"PIN", "ON", "OFF", "TIME", "FLOAT", "ID", "ALANGFILENAME", "WHITESPACE", 
		"NEWLINE", "BLOCKCOMMENT", "LINECOMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ALang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ALangParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ALangParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ALangParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StartContext : ParserRuleContext {
		public CommandsContext commands() {
			return GetRuleContext<CommandsContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(ALangParser.Eof, 0); }
		public StartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_start; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterStart(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitStart(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStart(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StartContext start() {
		StartContext _localctx = new StartContext(Context, State);
		EnterRule(_localctx, 0, RULE_start);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36; commands();
			State = 37; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandsContext : ParserRuleContext {
		public DclContext dcl() {
			return GetRuleContext<DclContext>(0);
		}
		public CommandsContext commands() {
			return GetRuleContext<CommandsContext>(0);
		}
		public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		public ImportsContext imports() {
			return GetRuleContext<ImportsContext>(0);
		}
		public CommandsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commands; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterCommands(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitCommands(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommands(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandsContext commands() {
		CommandsContext _localctx = new CommandsContext(Context, State);
		EnterRule(_localctx, 2, RULE_commands);
		try {
			State = 49;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case TYPE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 39; dcl();
				State = 40; commands();
				}
				break;
			case T__0:
				EnterOuterAlt(_localctx, 2);
				{
				State = 42; function();
				State = 43; commands();
				}
				break;
			case T__4:
				EnterOuterAlt(_localctx, 3);
				{
				State = 45; imports();
				State = 46; commands();
				}
				break;
			case Eof:
				EnterOuterAlt(_localctx, 4);
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DclContext : ParserRuleContext {
		public ITerminalNode TYPE() { return GetToken(ALangParser.TYPE, 0); }
		public ITerminalNode ID() { return GetToken(ALangParser.ID, 0); }
		public ITerminalNode ASSIGNOPERATOR() { return GetToken(ALangParser.ASSIGNOPERATOR, 0); }
		public PrimaryExpressionContext primaryExpression() {
			return GetRuleContext<PrimaryExpressionContext>(0);
		}
		public ITerminalNode ENDTERM() { return GetToken(ALangParser.ENDTERM, 0); }
		public DclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dcl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterDcl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitDcl(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDcl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DclContext dcl() {
		DclContext _localctx = new DclContext(Context, State);
		EnterRule(_localctx, 4, RULE_dcl);
		try {
			State = 60;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 51; Match(TYPE);
				State = 52; Match(ID);
				State = 53; Match(ASSIGNOPERATOR);
				State = 54; primaryExpression();
				State = 55; Match(ENDTERM);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 57; Match(TYPE);
				State = 58; Match(ID);
				State = 59; Match(ENDTERM);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(ALangParser.ID, 0); }
		public ParamsContext @params() {
			return GetRuleContext<ParamsContext>(0);
		}
		public ITerminalNode TYPE() { return GetToken(ALangParser.TYPE, 0); }
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 6, RULE_function);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62; Match(T__0);
			State = 63; Match(ID);
			State = 64; Match(T__1);
			State = 65; @params();
			State = 66; Match(T__2);
			State = 67; Match(TYPE);
			State = 68; stmts();
			State = 69; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImportsContext : ParserRuleContext {
		public ITerminalNode ALANGFILENAME() { return GetToken(ALangParser.ALANGFILENAME, 0); }
		public ITerminalNode ENDTERM() { return GetToken(ALangParser.ENDTERM, 0); }
		public ImportsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_imports; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterImports(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitImports(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImports(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImportsContext imports() {
		ImportsContext _localctx = new ImportsContext(Context, State);
		EnterRule(_localctx, 8, RULE_imports);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71; Match(T__4);
			State = 72; Match(ALANGFILENAME);
			State = 73; Match(ENDTERM);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrimaryExpressionContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode OPALL() { return GetToken(ALangParser.OPALL, 0); }
		public PrimaryExpressionContext primaryExpression() {
			return GetRuleContext<PrimaryExpressionContext>(0);
		}
		public PrimaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primaryExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterPrimaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitPrimaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrimaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrimaryExpressionContext primaryExpression() {
		PrimaryExpressionContext _localctx = new PrimaryExpressionContext(Context, State);
		EnterRule(_localctx, 10, RULE_primaryExpression);
		try {
			State = 80;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 75; expression();
				State = 76; Match(OPALL);
				State = 77; primaryExpression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 79; expression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ITerminalNode LPAREN() { return GetToken(ALangParser.LPAREN, 0); }
		public PrimaryExpressionContext primaryExpression() {
			return GetRuleContext<PrimaryExpressionContext>(0);
		}
		public ITerminalNode RPAREN() { return GetToken(ALangParser.RPAREN, 0); }
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 12, RULE_expression);
		try {
			State = 87;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTEGERS:
			case PIN:
			case TIME:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 82; value();
				}
				break;
			case LPAREN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 83; Match(LPAREN);
				State = 84; primaryExpression();
				State = 85; Match(RPAREN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParamsContext : ParserRuleContext {
		public ParamContext param() {
			return GetRuleContext<ParamContext>(0);
		}
		public ITerminalNode COMMA() { return GetToken(ALangParser.COMMA, 0); }
		public ParamsContext @params() {
			return GetRuleContext<ParamsContext>(0);
		}
		public ParamsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_params; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterParams(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitParams(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParams(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParamsContext @params() {
		ParamsContext _localctx = new ParamsContext(Context, State);
		EnterRule(_localctx, 14, RULE_params);
		try {
			State = 95;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 89; param();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 90; param();
				State = 91; Match(COMMA);
				State = 92; @params();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParamContext : ParserRuleContext {
		public ITerminalNode TYPE() { return GetToken(ALangParser.TYPE, 0); }
		public ITerminalNode ID() { return GetToken(ALangParser.ID, 0); }
		public ParamContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_param; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterParam(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitParam(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParam(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParamContext param() {
		ParamContext _localctx = new ParamContext(Context, State);
		EnterRule(_localctx, 16, RULE_param);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97; Match(TYPE);
			State = 98; Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtsContext : ParserRuleContext {
		public DclContext dcl() {
			return GetRuleContext<DclContext>(0);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public IfstmtContext ifstmt() {
			return GetRuleContext<IfstmtContext>(0);
		}
		public RepeatstmtContext repeatstmt() {
			return GetRuleContext<RepeatstmtContext>(0);
		}
		public OutputstmtContext outputstmt() {
			return GetRuleContext<OutputstmtContext>(0);
		}
		public ReturnstmtContext returnstmt() {
			return GetRuleContext<ReturnstmtContext>(0);
		}
		public FunctioncallContext functioncall() {
			return GetRuleContext<FunctioncallContext>(0);
		}
		public AssignstmtContext assignstmt() {
			return GetRuleContext<AssignstmtContext>(0);
		}
		public StmtsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmts; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterStmts(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitStmts(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmts(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtsContext stmts() {
		StmtsContext _localctx = new StmtsContext(Context, State);
		EnterRule(_localctx, 18, RULE_stmts);
		try {
			State = 122;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 100; dcl();
				State = 101; stmts();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 103; ifstmt();
				State = 104; stmts();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 106; repeatstmt();
				State = 107; stmts();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 109; outputstmt();
				State = 110; stmts();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 112; returnstmt();
				State = 113; stmts();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 115; functioncall();
				State = 116; stmts();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 118; assignstmt();
				State = 119; stmts();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignstmtContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(ALangParser.ID, 0); }
		public ITerminalNode ASSIGNOPERATOR() { return GetToken(ALangParser.ASSIGNOPERATOR, 0); }
		public PrimaryExpressionContext primaryExpression() {
			return GetRuleContext<PrimaryExpressionContext>(0);
		}
		public ITerminalNode ENDTERM() { return GetToken(ALangParser.ENDTERM, 0); }
		public AssignstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignstmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterAssignstmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitAssignstmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignstmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignstmtContext assignstmt() {
		AssignstmtContext _localctx = new AssignstmtContext(Context, State);
		EnterRule(_localctx, 20, RULE_assignstmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124; Match(ID);
			State = 125; Match(ASSIGNOPERATOR);
			State = 126; primaryExpression();
			State = 127; Match(ENDTERM);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfstmtContext : ParserRuleContext {
		public ITerminalNode IF() { return GetToken(ALangParser.IF, 0); }
		public PrimaryExpressionContext primaryExpression() {
			return GetRuleContext<PrimaryExpressionContext>(0);
		}
		public ITerminalNode THEN() { return GetToken(ALangParser.THEN, 0); }
		public StmtsContext[] stmts() {
			return GetRuleContexts<StmtsContext>();
		}
		public StmtsContext stmts(int i) {
			return GetRuleContext<StmtsContext>(i);
		}
		public ITerminalNode ENDIF() { return GetToken(ALangParser.ENDIF, 0); }
		public ITerminalNode ELSE() { return GetToken(ALangParser.ELSE, 0); }
		public IfstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifstmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterIfstmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitIfstmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfstmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfstmtContext ifstmt() {
		IfstmtContext _localctx = new IfstmtContext(Context, State);
		EnterRule(_localctx, 22, RULE_ifstmt);
		try {
			State = 143;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 129; Match(IF);
				State = 130; primaryExpression();
				State = 131; Match(THEN);
				State = 132; stmts();
				State = 133; Match(ENDIF);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 135; Match(IF);
				State = 136; primaryExpression();
				State = 137; Match(THEN);
				State = 138; stmts();
				State = 139; Match(ELSE);
				State = 140; stmts();
				State = 141; Match(ENDIF);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RepeatstmtContext : ParserRuleContext {
		public PrimaryExpressionContext primaryExpression() {
			return GetRuleContext<PrimaryExpressionContext>(0);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public RepeatstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_repeatstmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterRepeatstmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitRepeatstmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRepeatstmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RepeatstmtContext repeatstmt() {
		RepeatstmtContext _localctx = new RepeatstmtContext(Context, State);
		EnterRule(_localctx, 24, RULE_repeatstmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 145; Match(T__5);
			State = 146; primaryExpression();
			State = 147; Match(T__6);
			State = 148; stmts();
			State = 149; Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OutputstmtContext : ParserRuleContext {
		public ITerminalNode ON() { return GetToken(ALangParser.ON, 0); }
		public ITerminalNode ID() { return GetToken(ALangParser.ID, 0); }
		public ITerminalNode ENDTERM() { return GetToken(ALangParser.ENDTERM, 0); }
		public ITerminalNode OFF() { return GetToken(ALangParser.OFF, 0); }
		public OutputstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_outputstmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterOutputstmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitOutputstmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOutputstmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OutputstmtContext outputstmt() {
		OutputstmtContext _localctx = new OutputstmtContext(Context, State);
		EnterRule(_localctx, 26, RULE_outputstmt);
		try {
			State = 159;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ON:
				EnterOuterAlt(_localctx, 1);
				{
				State = 151; Match(ON);
				State = 152; Match(T__1);
				State = 153; Match(ID);
				State = 154; Match(ENDTERM);
				}
				break;
			case OFF:
				EnterOuterAlt(_localctx, 2);
				{
				State = 155; Match(OFF);
				State = 156; Match(T__1);
				State = 157; Match(ID);
				State = 158; Match(ENDTERM);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnstmtContext : ParserRuleContext {
		public PrimaryExpressionContext primaryExpression() {
			return GetRuleContext<PrimaryExpressionContext>(0);
		}
		public ITerminalNode ENDTERM() { return GetToken(ALangParser.ENDTERM, 0); }
		public ReturnstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnstmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterReturnstmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitReturnstmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturnstmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReturnstmtContext returnstmt() {
		ReturnstmtContext _localctx = new ReturnstmtContext(Context, State);
		EnterRule(_localctx, 28, RULE_returnstmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 161; Match(T__8);
			State = 162; primaryExpression();
			State = 163; Match(ENDTERM);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctioncallContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(ALangParser.ID, 0); }
		public InputparamsContext inputparams() {
			return GetRuleContext<InputparamsContext>(0);
		}
		public ITerminalNode ENDTERM() { return GetToken(ALangParser.ENDTERM, 0); }
		public FunctioncallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functioncall; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterFunctioncall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitFunctioncall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctioncall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctioncallContext functioncall() {
		FunctioncallContext _localctx = new FunctioncallContext(Context, State);
		EnterRule(_localctx, 30, RULE_functioncall);
		try {
			State = 173;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 165; Match(ID);
				State = 166; Match(T__1);
				State = 167; inputparams();
				State = 168; Match(ENDTERM);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 170; Match(ID);
				State = 171; Match(T__1);
				State = 172; Match(ENDTERM);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InputparamsContext : ParserRuleContext {
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ITerminalNode COMMA() { return GetToken(ALangParser.COMMA, 0); }
		public InputparamsContext inputparams() {
			return GetRuleContext<InputparamsContext>(0);
		}
		public InputparamsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_inputparams; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterInputparams(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitInputparams(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInputparams(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InputparamsContext inputparams() {
		InputparamsContext _localctx = new InputparamsContext(Context, State);
		EnterRule(_localctx, 32, RULE_inputparams);
		try {
			State = 180;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 175; value();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 176; value();
				State = 177; Match(COMMA);
				State = 178; inputparams();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(ALangParser.ID, 0); }
		public ITerminalNode INTEGERS() { return GetToken(ALangParser.INTEGERS, 0); }
		public ITerminalNode PIN() { return GetToken(ALangParser.PIN, 0); }
		public ITerminalNode TIME() { return GetToken(ALangParser.TIME, 0); }
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IALangListener typedListener = listener as IALangListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IALangVisitor<TResult> typedVisitor = visitor as IALangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 34, RULE_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 182;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INTEGERS) | (1L << PIN) | (1L << TIME) | (1L << ID))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\'', '\xBB', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '\x34', 
		'\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', 
		'\x4', '?', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', 
		'S', '\n', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x5', '\b', 'Z', '\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\x62', '\n', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', '}', '\n', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x5', '\r', '\x92', '\n', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', '\xA2', '\n', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\xB0', '\n', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x5', '\x12', '\xB7', '\n', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x2', '\x2', '\x14', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', 
		'\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', 
		'$', '\x2', '\x3', '\x5', '\x2', '\x1C', '\x1D', ' ', ' ', '\"', '\"', 
		'\x2', '\xBB', '\x2', '&', '\x3', '\x2', '\x2', '\x2', '\x4', '\x33', 
		'\x3', '\x2', '\x2', '\x2', '\x6', '>', '\x3', '\x2', '\x2', '\x2', '\b', 
		'@', '\x3', '\x2', '\x2', '\x2', '\n', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\f', 'R', '\x3', '\x2', '\x2', '\x2', '\xE', 'Y', '\x3', '\x2', '\x2', 
		'\x2', '\x10', '\x61', '\x3', '\x2', '\x2', '\x2', '\x12', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x14', '|', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x18', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '\x1A', '\x93', '\x3', '\x2', '\x2', '\x2', '\x1C', '\xA1', '\x3', 
		'\x2', '\x2', '\x2', '\x1E', '\xA3', '\x3', '\x2', '\x2', '\x2', ' ', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\"', '\xB6', '\x3', '\x2', '\x2', 
		'\x2', '$', '\xB8', '\x3', '\x2', '\x2', '\x2', '&', '\'', '\x5', '\x4', 
		'\x3', '\x2', '\'', '(', '\a', '\x2', '\x2', '\x3', '(', '\x3', '\x3', 
		'\x2', '\x2', '\x2', ')', '*', '\x5', '\x6', '\x4', '\x2', '*', '+', '\x5', 
		'\x4', '\x3', '\x2', '+', '\x34', '\x3', '\x2', '\x2', '\x2', ',', '-', 
		'\x5', '\b', '\x5', '\x2', '-', '.', '\x5', '\x4', '\x3', '\x2', '.', 
		'\x34', '\x3', '\x2', '\x2', '\x2', '/', '\x30', '\x5', '\n', '\x6', '\x2', 
		'\x30', '\x31', '\x5', '\x4', '\x3', '\x2', '\x31', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\x32', '\x34', '\x3', '\x2', '\x2', '\x2', '\x33', ')', 
		'\x3', '\x2', '\x2', '\x2', '\x33', ',', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x33', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x34', '\x5', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', 
		'\x15', '\x2', '\x2', '\x36', '\x37', '\a', '\"', '\x2', '\x2', '\x37', 
		'\x38', '\a', '\x19', '\x2', '\x2', '\x38', '\x39', '\x5', '\f', '\a', 
		'\x2', '\x39', ':', '\a', '\xE', '\x2', '\x2', ':', '?', '\x3', '\x2', 
		'\x2', '\x2', ';', '<', '\a', '\x15', '\x2', '\x2', '<', '=', '\a', '\"', 
		'\x2', '\x2', '=', '?', '\a', '\xE', '\x2', '\x2', '>', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '>', ';', '\x3', '\x2', '\x2', '\x2', '?', '\a', 
		'\x3', '\x2', '\x2', '\x2', '@', '\x41', '\a', '\x3', '\x2', '\x2', '\x41', 
		'\x42', '\a', '\"', '\x2', '\x2', '\x42', '\x43', '\a', '\x4', '\x2', 
		'\x2', '\x43', '\x44', '\x5', '\x10', '\t', '\x2', '\x44', '\x45', '\a', 
		'\x5', '\x2', '\x2', '\x45', '\x46', '\a', '\x15', '\x2', '\x2', '\x46', 
		'G', '\x5', '\x14', '\v', '\x2', 'G', 'H', '\a', '\x6', '\x2', '\x2', 
		'H', '\t', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', '\a', '\x2', '\x2', 
		'J', 'K', '\a', '#', '\x2', '\x2', 'K', 'L', '\a', '\xE', '\x2', '\x2', 
		'L', '\v', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\x5', '\xE', '\b', '\x2', 
		'N', 'O', '\a', '\x1A', '\x2', '\x2', 'O', 'P', '\x5', '\f', '\a', '\x2', 
		'P', 'S', '\x3', '\x2', '\x2', '\x2', 'Q', 'S', '\x5', '\xE', '\b', '\x2', 
		'R', 'M', '\x3', '\x2', '\x2', '\x2', 'R', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'S', '\r', '\x3', '\x2', '\x2', '\x2', 'T', 'Z', '\x5', '$', '\x13', '\x2', 
		'U', 'V', '\a', '\x16', '\x2', '\x2', 'V', 'W', '\x5', '\f', '\a', '\x2', 
		'W', 'X', '\a', '\x17', '\x2', '\x2', 'X', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'Y', 'T', '\x3', '\x2', '\x2', '\x2', 'Y', 'U', '\x3', '\x2', '\x2', '\x2', 
		'Z', '\xF', '\x3', '\x2', '\x2', '\x2', '[', '\x62', '\x5', '\x12', '\n', 
		'\x2', '\\', ']', '\x5', '\x12', '\n', '\x2', ']', '^', '\a', '\x18', 
		'\x2', '\x2', '^', '_', '\x5', '\x10', '\t', '\x2', '_', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '`', '\x62', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'[', '\x3', '\x2', '\x2', '\x2', '\x61', '\\', '\x3', '\x2', '\x2', '\x2', 
		'\x61', '`', '\x3', '\x2', '\x2', '\x2', '\x62', '\x11', '\x3', '\x2', 
		'\x2', '\x2', '\x63', '\x64', '\a', '\x15', '\x2', '\x2', '\x64', '\x65', 
		'\a', '\"', '\x2', '\x2', '\x65', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x66', 'g', '\x5', '\x6', '\x4', '\x2', 'g', 'h', '\x5', '\x14', '\v', 
		'\x2', 'h', '}', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\x5', '\x18', 
		'\r', '\x2', 'j', 'k', '\x5', '\x14', '\v', '\x2', 'k', '}', '\x3', '\x2', 
		'\x2', '\x2', 'l', 'm', '\x5', '\x1A', '\xE', '\x2', 'm', 'n', '\x5', 
		'\x14', '\v', '\x2', 'n', '}', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\x5', 
		'\x1C', '\xF', '\x2', 'p', 'q', '\x5', '\x14', '\v', '\x2', 'q', '}', 
		'\x3', '\x2', '\x2', '\x2', 'r', 's', '\x5', '\x1E', '\x10', '\x2', 's', 
		't', '\x5', '\x14', '\v', '\x2', 't', '}', '\x3', '\x2', '\x2', '\x2', 
		'u', 'v', '\x5', ' ', '\x11', '\x2', 'v', 'w', '\x5', '\x14', '\v', '\x2', 
		'w', '}', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\x5', '\x16', '\f', '\x2', 
		'y', 'z', '\x5', '\x14', '\v', '\x2', 'z', '}', '\x3', '\x2', '\x2', '\x2', 
		'{', '}', '\x3', '\x2', '\x2', '\x2', '|', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '|', 'i', '\x3', '\x2', '\x2', '\x2', '|', 'l', '\x3', '\x2', '\x2', 
		'\x2', '|', 'o', '\x3', '\x2', '\x2', '\x2', '|', 'r', '\x3', '\x2', '\x2', 
		'\x2', '|', 'u', '\x3', '\x2', '\x2', '\x2', '|', 'x', '\x3', '\x2', '\x2', 
		'\x2', '|', '{', '\x3', '\x2', '\x2', '\x2', '}', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '~', '\x7F', '\a', '\"', '\x2', '\x2', '\x7F', '\x80', '\a', 
		'\x19', '\x2', '\x2', '\x80', '\x81', '\x5', '\f', '\a', '\x2', '\x81', 
		'\x82', '\a', '\xE', '\x2', '\x2', '\x82', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x84', '\a', '\xF', '\x2', '\x2', '\x84', '\x85', '\x5', 
		'\f', '\a', '\x2', '\x85', '\x86', '\a', '\x14', '\x2', '\x2', '\x86', 
		'\x87', '\x5', '\x14', '\v', '\x2', '\x87', '\x88', '\a', '\f', '\x2', 
		'\x2', '\x88', '\x92', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\a', 
		'\xF', '\x2', '\x2', '\x8A', '\x8B', '\x5', '\f', '\a', '\x2', '\x8B', 
		'\x8C', '\a', '\x14', '\x2', '\x2', '\x8C', '\x8D', '\x5', '\x14', '\v', 
		'\x2', '\x8D', '\x8E', '\a', '\x11', '\x2', '\x2', '\x8E', '\x8F', '\x5', 
		'\x14', '\v', '\x2', '\x8F', '\x90', '\a', '\f', '\x2', '\x2', '\x90', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x91', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x91', '\x89', '\x3', '\x2', '\x2', '\x2', '\x92', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x94', '\a', '\b', '\x2', '\x2', '\x94', 
		'\x95', '\x5', '\f', '\a', '\x2', '\x95', '\x96', '\a', '\t', '\x2', '\x2', 
		'\x96', '\x97', '\x5', '\x14', '\v', '\x2', '\x97', '\x98', '\a', '\n', 
		'\x2', '\x2', '\x98', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', 
		'\a', '\x1E', '\x2', '\x2', '\x9A', '\x9B', '\a', '\x4', '\x2', '\x2', 
		'\x9B', '\x9C', '\a', '\"', '\x2', '\x2', '\x9C', '\xA2', '\a', '\xE', 
		'\x2', '\x2', '\x9D', '\x9E', '\a', '\x1F', '\x2', '\x2', '\x9E', '\x9F', 
		'\a', '\x4', '\x2', '\x2', '\x9F', '\xA0', '\a', '\"', '\x2', '\x2', '\xA0', 
		'\xA2', '\a', '\xE', '\x2', '\x2', '\xA1', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\x9D', '\x3', '\x2', '\x2', '\x2', '\xA2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\xA3', '\xA4', '\a', '\v', '\x2', '\x2', '\xA4', 
		'\xA5', '\x5', '\f', '\a', '\x2', '\xA5', '\xA6', '\a', '\xE', '\x2', 
		'\x2', '\xA6', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\a', 
		'\"', '\x2', '\x2', '\xA8', '\xA9', '\a', '\x4', '\x2', '\x2', '\xA9', 
		'\xAA', '\x5', '\"', '\x12', '\x2', '\xAA', '\xAB', '\a', '\xE', '\x2', 
		'\x2', '\xAB', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\a', 
		'\"', '\x2', '\x2', '\xAD', '\xAE', '\a', '\x4', '\x2', '\x2', '\xAE', 
		'\xB0', '\a', '\xE', '\x2', '\x2', '\xAF', '\xA7', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xB0', '!', '\x3', 
		'\x2', '\x2', '\x2', '\xB1', '\xB7', '\x5', '$', '\x13', '\x2', '\xB2', 
		'\xB3', '\x5', '$', '\x13', '\x2', '\xB3', '\xB4', '\a', '\x18', '\x2', 
		'\x2', '\xB4', '\xB5', '\x5', '\"', '\x12', '\x2', '\xB5', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB6', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', '\xB7', '#', '\x3', '\x2', '\x2', 
		'\x2', '\xB8', '\xB9', '\t', '\x2', '\x2', '\x2', '\xB9', '%', '\x3', 
		'\x2', '\x2', '\x2', '\f', '\x33', '>', 'R', 'Y', '\x61', '|', '\x91', 
		'\xA1', '\xAF', '\xB6',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace AntlrGen
