//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/aaspr.DESKTOP-G6R73JT/OneDrive/Desktop/flytning/p4-compiler/alang_compile/core_compile\ALang.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrGen {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ALangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IALangListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] ALangParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] ALangParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.stmts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmts([NotNull] ALangParser.StmtsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.stmts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmts([NotNull] ALangParser.StmtsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] ALangParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] ALangParser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.dcls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDcls([NotNull] ALangParser.DclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.dcls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDcls([NotNull] ALangParser.DclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDcl([NotNull] ALangParser.DclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDcl([NotNull] ALangParser.DclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.assignstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignstmt([NotNull] ALangParser.AssignstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.assignstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignstmt([NotNull] ALangParser.AssignstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfstmt([NotNull] ALangParser.IfstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfstmt([NotNull] ALangParser.IfstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.repeatstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatstmt([NotNull] ALangParser.RepeatstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.repeatstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatstmt([NotNull] ALangParser.RepeatstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.outputstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputstmt([NotNull] ALangParser.OutputstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.outputstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputstmt([NotNull] ALangParser.OutputstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] ALangParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] ALangParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALangParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ALangParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALangParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ALangParser.ValueContext context);
}
} // namespace AntlrGen
